//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranvaroWeb.FranvaroServiceReferance {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FranvaroDB", Namespace="http://schemas.datacontract.org/2004/07/E_projektService3")]
    [System.SerializableAttribute()]
    public partial class FranvaroDB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnstallningsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_postField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FranvaroOrsakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReferensIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TelefonnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eNamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fNamnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnstallningsID {
            get {
                return this.AnstallningsIDField;
            }
            set {
                if ((this.AnstallningsIDField.Equals(value) != true)) {
                    this.AnstallningsIDField = value;
                    this.RaisePropertyChanged("AnstallningsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((object.ReferenceEquals(this.DatumField, value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_post {
            get {
                return this.E_postField;
            }
            set {
                if ((object.ReferenceEquals(this.E_postField, value) != true)) {
                    this.E_postField = value;
                    this.RaisePropertyChanged("E_post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FranvaroOrsak {
            get {
                return this.FranvaroOrsakField;
            }
            set {
                if ((object.ReferenceEquals(this.FranvaroOrsakField, value) != true)) {
                    this.FranvaroOrsakField = value;
                    this.RaisePropertyChanged("FranvaroOrsak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferensID {
            get {
                return this.ReferensIDField;
            }
            set {
                if ((this.ReferensIDField.Equals(value) != true)) {
                    this.ReferensIDField = value;
                    this.RaisePropertyChanged("ReferensID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Telefonnummer {
            get {
                return this.TelefonnummerField;
            }
            set {
                if ((this.TelefonnummerField.Equals(value) != true)) {
                    this.TelefonnummerField = value;
                    this.RaisePropertyChanged("Telefonnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tid {
            get {
                return this.TidField;
            }
            set {
                if ((object.ReferenceEquals(this.TidField, value) != true)) {
                    this.TidField = value;
                    this.RaisePropertyChanged("Tid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eNamn {
            get {
                return this.eNamnField;
            }
            set {
                if ((object.ReferenceEquals(this.eNamnField, value) != true)) {
                    this.eNamnField = value;
                    this.RaisePropertyChanged("eNamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fNamn {
            get {
                return this.fNamnField;
            }
            set {
                if ((object.ReferenceEquals(this.fNamnField, value) != true)) {
                    this.fNamnField = value;
                    this.RaisePropertyChanged("fNamn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusLista", Namespace="http://schemas.datacontract.org/2004/07/E_projektService3")]
    [System.SerializableAttribute()]
    public partial class StatusLista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnstallningsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FranvaroOrsakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReferensIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fNamnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnstallningsID {
            get {
                return this.AnstallningsIDField;
            }
            set {
                if ((this.AnstallningsIDField.Equals(value) != true)) {
                    this.AnstallningsIDField = value;
                    this.RaisePropertyChanged("AnstallningsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((object.ReferenceEquals(this.DatumField, value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FranvaroOrsak {
            get {
                return this.FranvaroOrsakField;
            }
            set {
                if ((object.ReferenceEquals(this.FranvaroOrsakField, value) != true)) {
                    this.FranvaroOrsakField = value;
                    this.RaisePropertyChanged("FranvaroOrsak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferensID {
            get {
                return this.ReferensIDField;
            }
            set {
                if ((this.ReferensIDField.Equals(value) != true)) {
                    this.ReferensIDField = value;
                    this.RaisePropertyChanged("ReferensID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tid {
            get {
                return this.TidField;
            }
            set {
                if ((object.ReferenceEquals(this.TidField, value) != true)) {
                    this.TidField = value;
                    this.RaisePropertyChanged("Tid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fNamn {
            get {
                return this.fNamnField;
            }
            set {
                if ((object.ReferenceEquals(this.fNamnField, value) != true)) {
                    this.fNamnField = value;
                    this.RaisePropertyChanged("fNamn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FranvaroServiceReferance.IAnmalanService1")]
    public interface IAnmalanService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnmalanService1/getAnmalan", ReplyAction="http://tempuri.org/IAnmalanService1/getAnmalanResponse")]
        FranvaroWeb.FranvaroServiceReferance.FranvaroDB[] getAnmalan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnmalanService1/getAnmalan", ReplyAction="http://tempuri.org/IAnmalanService1/getAnmalanResponse")]
        System.Threading.Tasks.Task<FranvaroWeb.FranvaroServiceReferance.FranvaroDB[]> getAnmalanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnmalanService1/getStatusLista", ReplyAction="http://tempuri.org/IAnmalanService1/getStatusListaResponse")]
        FranvaroWeb.FranvaroServiceReferance.StatusLista[] getStatusLista(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnmalanService1/getStatusLista", ReplyAction="http://tempuri.org/IAnmalanService1/getStatusListaResponse")]
        System.Threading.Tasks.Task<FranvaroWeb.FranvaroServiceReferance.StatusLista[]> getStatusListaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnmalanService1/getSpecificAnmalan", ReplyAction="http://tempuri.org/IAnmalanService1/getSpecificAnmalanResponse")]
        FranvaroWeb.FranvaroServiceReferance.FranvaroDB[] getSpecificAnmalan(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnmalanService1/getSpecificAnmalan", ReplyAction="http://tempuri.org/IAnmalanService1/getSpecificAnmalanResponse")]
        System.Threading.Tasks.Task<FranvaroWeb.FranvaroServiceReferance.FranvaroDB[]> getSpecificAnmalanAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnmalanService1/sparaStatus", ReplyAction="http://tempuri.org/IAnmalanService1/sparaStatusResponse")]
        string sparaStatus(string fNamn, string eNamn, string adress, int Telefonnummer, string epost, int Anstallningsid, string franVaroOrsak, string tid, string datum, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnmalanService1/sparaStatus", ReplyAction="http://tempuri.org/IAnmalanService1/sparaStatusResponse")]
        System.Threading.Tasks.Task<string> sparaStatusAsync(string fNamn, string eNamn, string adress, int Telefonnummer, string epost, int Anstallningsid, string franVaroOrsak, string tid, string datum, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnmalanService1Channel : FranvaroWeb.FranvaroServiceReferance.IAnmalanService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnmalanService1Client : System.ServiceModel.ClientBase<FranvaroWeb.FranvaroServiceReferance.IAnmalanService1>, FranvaroWeb.FranvaroServiceReferance.IAnmalanService1 {
        
        public AnmalanService1Client() {
        }
        
        public AnmalanService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnmalanService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnmalanService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnmalanService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FranvaroWeb.FranvaroServiceReferance.FranvaroDB[] getAnmalan() {
            return base.Channel.getAnmalan();
        }
        
        public System.Threading.Tasks.Task<FranvaroWeb.FranvaroServiceReferance.FranvaroDB[]> getAnmalanAsync() {
            return base.Channel.getAnmalanAsync();
        }
        
        public FranvaroWeb.FranvaroServiceReferance.StatusLista[] getStatusLista(int id) {
            return base.Channel.getStatusLista(id);
        }
        
        public System.Threading.Tasks.Task<FranvaroWeb.FranvaroServiceReferance.StatusLista[]> getStatusListaAsync(int id) {
            return base.Channel.getStatusListaAsync(id);
        }
        
        public FranvaroWeb.FranvaroServiceReferance.FranvaroDB[] getSpecificAnmalan(int id) {
            return base.Channel.getSpecificAnmalan(id);
        }
        
        public System.Threading.Tasks.Task<FranvaroWeb.FranvaroServiceReferance.FranvaroDB[]> getSpecificAnmalanAsync(int id) {
            return base.Channel.getSpecificAnmalanAsync(id);
        }
        
        public string sparaStatus(string fNamn, string eNamn, string adress, int Telefonnummer, string epost, int Anstallningsid, string franVaroOrsak, string tid, string datum, string status) {
            return base.Channel.sparaStatus(fNamn, eNamn, adress, Telefonnummer, epost, Anstallningsid, franVaroOrsak, tid, datum, status);
        }
        
        public System.Threading.Tasks.Task<string> sparaStatusAsync(string fNamn, string eNamn, string adress, int Telefonnummer, string epost, int Anstallningsid, string franVaroOrsak, string tid, string datum, string status) {
            return base.Channel.sparaStatusAsync(fNamn, eNamn, adress, Telefonnummer, epost, Anstallningsid, franVaroOrsak, tid, datum, status);
        }
    }
}
