//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FranvaroWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalLista
    {
        public int AnställningsID { get; set; }
        public string Fnamn { get; set; }
        public string Enamn { get; set; }
        public string Telefonnummer { get; set; }
        public string E_mail { get; set; }
        public string Lösenord { get; set; }
    }
}
